### ISSUE TITLE
Error when executing getTradesSummary

### ISSUE THREAD

**Issue by cm45t3r** [tradalize/core#27]
Hi,

Following your example code at tradalize/create-tradalize-app, I found the getTradesSummary has an error:

```typescript
console.info(getTradesSummary(broker.positionsList.toArray()));
```

Result:

```typescript
~/backtest.tradalize/node_modules/@tradalize/core/dist/utils/math.js:8
  return numbers.reduce(add) / numbers.length;
                 ^


TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at average (/Users/curibe/workspace/backtest.tradalize/node_modules/@tradalize/core/dist/utils/math.js:8:18)
    at getTradesSummary (/Users/curibe/workspace/backtest.tradalize/node_modules/@tradalize/core/dist/analitic/tradesSummary.js:41:37)
    at main (/Users/curibe/workspace/backtest.tradalize/src/backtest.ts:18:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.7.3
```

**Comment by Besmerch123** [comment]
@cm45t3r  Thanks for this issue. I was also annoyed by this error in my work but was too lazy to fix it for myself.

Use version ^0.5.5 since now)
